#good tutorial https://github.com/squidfunk/mkdocs-material/discussions/2346
site_name: Burni docs
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
theme:
  name: material
  features:
    - content.tabs.link
  language: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 繁體中文
      link: /zh-TW
      lang: zh-TW

nav:
 - Home: index.md
 - Introduction: Introduction.md
 - Getting Started:
    - Installation: Getting started/Installation.md
    - Configuration: Getting started/Configuration.md
    - Deploy: Getting started/Deploy.md
 - FHIR API Documentation:
    - Overview: FHIR API Documentation/Overview.md
    - Generate OpenAPI: FHIR API Documentation/Generate OpenAPI.md
 - Search Parameters: 
    - Overview: SearchParameter/Overview.md
    - Add search parameter: SearchParameter/Add_SearchParameter.md
    